### ISSUE TITLE
Prompt template is not adapted to the dataset

### ISSUE THREAD

**Issue by m-krastev** [danilotpnta/IR2-project#4]
# Adaptive Prompt Template

Issues:
- Currently, the provided templates in `prompts` are relatively hard-coded for all datasets.
- The templates were designed for not very good models. If we use Llama3+, it might be better to at least ask the model to generate more queries.
- Would be good if the templates were adapted to the specific dataset, e.g. for `webqsp`, the template could be "What is the answer to the question: {question}?".

**Comment by MJHamar** [comment]
can't we just fit a prompt with dspy instead of trying to hard-code new ones?

**Comment by m-krastev** [comment]
Issue is, it might not be very compute-efficient. We can try to generate one prompt per dataset. I need to say that I am thinking along the lines of using a 70B+ model for generation. If we only use <=8B models, this concern is not as real at all.

**Comment by m-krastev** [comment]
Partially resolved using DSPy and DynamicPrompt in #5 and #6.

**Comment by m-krastev** [comment]
Partially resolved using DSPy and DynamicPrompt in https://github.com/danilotpnta/IR2-project/pull/5 and https://github.com/danilotpnta/IR2-project/pull/6.
